PayBackOffice:
    PayInvoicePortalResetPasswordLink:
        settings-key: InvoicePortalResetPasswordLink
    BlockchainExplorerUrl:
        settings-key: PayInvoicePortalBlockchainExplorerUrl
    EthereumBlockchainExplorerUrl: 
        settings-key: EthereumBlockchainExplorerUrl
    Db:
        LogsConnString: 
            settings-key: PayBackOffice-LogsConnString
            types: [ AzureTableStorage, Tag ]
        LykkePayWalletList:
            Wallets: 
                settings-key: PayBackOffice-LykkePayWalletList-Wallets
                types: [ JsonArray, Tag ]
        SupportedBrowsers:
            Browsers:
                settings-key: PayBackOffice-SupportedBrowsers-Browsers
                types: [ JsonArray ]
            SkipUrls:
                settings-key: PayBackOffice-SupportedBrowsers-SkipUrls
                types: [ JsonArray ]
        GoogleAuthSettings:
            ApiClientId:
                settings-key: PayBackOffice-GoogleAuthSettings-ApiClientId
            AvailableEmailsRegex:
                settings-key: PayBackOffice-GoogleAuthSettings-AvailableEmailsRegex
            DefaultAdminEmail: 
                settings-key: PayBackOffice-GoogleAuthSettings-DefaultAdminEmail
        TwoFactorVerification:
            UseVerification:
                settings-key: PayBackOffice-TwoFactorVerification-UseVerification
    PayInternalServiceClient:
        ServiceUrl: 
            settings-key: PayInternalServiceUrl
            types: [ Tag ]
    PayInvoiceServiceClient:
        ServiceUrl: 
            settings-key: PayInvoiceServiceUrl
            types: [ Tag ]
    BackofficeMembershipServiceClient:
        ServiceUrl: 
            settings-key: BackofficeMembershipServiceUrl
    EmailPartnerRouterServiceClient:
        ServiceUrl: 
            settings-key: EmailPartnerRouterServiceUrl
    NinjaServiceClient:
        ServiceUrl:
            settings-key: NinjaServiceUrl
            types: [ Tag ]
    PayAuthServiceClient:
        ServiceUrl: 
            settings-key: PayAuthServiceUrl
            types: [ Tag ]

MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl

SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types: [ AzureTableStorage ]
    QueueName:
      settings-key: SlackQueueName
      types: [ AzureTableStorage ]